import type { Metadata } from 'next';
import { Content, Inter } from 'next/font/google';
import '@/styles/globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { supabase } from '@/lib/initSupabase';
import { Auth } from '@supabase/auth-ui-react';
import { ThemeSupa } from '@supabase/auth-ui-shared';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          ' bg-gradient-to-b from-white via-orange-500 to-black'
        }
      >
        <main className="min-h-screen flex flex-col justify-center items-center">
          {/* Assuming Navbar is transparent */}
          <Navbar />

          {/* Give children some space around (here using padding for example) */}
          <div className="relative w-5/6 max-w-2xl mx-auto my-12 bg-transparent">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
