import type { Metadata } from 'next';
import { Content, Inter } from 'next/font/google';
import '@/styles/globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          ' bg-gradient-to-b from-white via-orange-500 to-black'
        }
      >
        <main className="min-h-screen flex flex-col justify-center items-center">
          <div className="relative w-5/6 max-w-2xl mx-auto my-12 bg-transparent">
            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
