const posts = [
  {
    id: 1,
    title: 'Review of The Shire Journey',
    content: 'The first book in an epic fantasy saga...',
    createdAt: new Date(2021, 10, 5),
    rating: 4,
    tag: 'Fantasy',
    book: 'The Shire Journey',
  },
  {
    id: 2,
    title: 'Insights of Mars Chronicles',
    content: "A thrilling novel about humanity's colonization of Mars...",
    createdAt: new Date(2021, 11, 15),
    rating: 5,
    tag: 'Science Fiction',
    book: 'Mars Chronicles',
  },
  {
    id: 3,
    title: 'Exploring the Dark Manor',
    content: 'A suspenseful mystery about a haunted mansion...',
    createdAt: new Date(2022, 0, 20),
    rating: 3,
    tag: 'Mystery',
    book: 'Dark Manor',
  },
  {
    id: 4,
    title: 'A review of Empower Yourself',
    content: 'The essential guide to take control of your life...',
    createdAt: new Date(2022, 1, 3),
    rating: 5,
    tag: 'self-help',
    book: 'Empower Yourself',
  },
  {
    id: 5,
    title: 'The life of Steve Jobs',
    content: "An in-depth look at the innovator's life and legacy...",
    createdAt: new Date(2022, 0, 27),
    rating: 4,
    tag: 'biography',
    book: 'Steve Jobs',
  },
  {
    id: 6,
    title: "Diving into the Sword's Lore",
    content: 'Detailing the rise of a hero in an enchanted world...',
    createdAt: new Date(2022, 1, 12),
    rating: 5,
    tag: 'Fantasy',
    book: "Sword's Lore",
  },
  {
    id: 7,
    title: 'The Enigma of Space Pirates',
    content: 'A captivating tale of interstellar buccaneers...',
    createdAt: new Date(2022, 0, 16),
    rating: 4,
    tag: 'Science Fiction',
    book: 'Space Pirates',
  },
  {
    id: 8,
    title: 'Discussion on The Whodunit Affair',
    content: 'Investigating a classic whodunit in a sleepy town...',
    createdAt: new Date(2022, 0, 24),
    rating: 5,
    tag: 'Mystery',
    book: 'Whodunit Affair',
  },
  {
    id: 9,
    title: 'The journey of Reinventing Yourself',
    content: 'Chronicling the step-by-step process of self-improvement...',
    createdAt: new Date(2022, 1, 8),
    rating: 4,
    tag: 'self-help',
    book: 'Reinventing Yourself',
  },
  {
    id: 10,
    title: 'About the book Elon Musk',
    content: 'Understanding the vision and ambition of a tech magnate...',
    createdAt: new Date(2022, 1, 13),
    rating: 5,
    tag: 'biography',
    book: 'Elon Musk',
  },
];

export default posts;
